name: Testception

on: [push, pull_request]

jobs:
  test:
    name: 'Test job'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # - uses: mxschmitt/action-tmate@v1
      - name: 'Uses itself'
        # Special case with the repo itself 
        uses: ./
